In [1]:
import numpy as np

# Calculations in arrays

In [3]:
a=np.arange(10,20)

In [4]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
x=a%2==0
a[x]

array([10, 12, 14, 16, 18])

In [7]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b=np.array([1,2,8,4,15,16,17,18,19])

In [10]:
b

array([ 1,  2,  8,  4, 15, 16, 17, 18, 19])

In [11]:
x=a==b

In [12]:
x

array([ True,  True, False,  True, False, False, False, False, False])

In [13]:
a[x]

array([1, 2, 4])

In [14]:
a[a==b]

array([1, 2, 4])

In [15]:
a=np.array([1,6,9,4,8,6,7,8])

In [16]:
a

array([1, 6, 9, 4, 8, 6, 7, 8])

In [17]:
x=(a>5)&(a<10)

In [18]:
x

array([False,  True,  True, False,  True,  True,  True,  True])

In [19]:
a[x]

array([6, 9, 8, 6, 7, 8])

In [20]:
a=np.array([19,20,21,44,55,29,34])

In [21]:
a

array([19, 20, 21, 44, 55, 29, 34])

In [22]:
# divisible of 5
x=a%5==0

In [23]:
x

array([False,  True, False, False,  True, False, False])

In [24]:
a[x]

array([20, 55])