In [1]:
import numpy as np

# Slicing for 1D array

In [2]:
a1=np.array([11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [4]:
a1[1:4]
# here 1 is inclusive and tha 4 is exclusive

array([12, 13, 14])

In [5]:
# if we not provide the ending value then it takes auto
a1[4:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
# if we want to take first four elements then 
a1[:4]

array([11, 12, 13, 14])

# Slicing for 2D array

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[0][0]

1

In [10]:
a[1:2,2:]

array([[6]])

# broadcasting    

In [11]:
a=np.array([1,2,3])

In [12]:
a

array([1, 2, 3])

In [13]:
b=4

In [14]:
a+b

array([5, 6, 7])

In [15]:
a=np.array([[1,2,3,],[4,5,6]])

In [16]:
b=np.array([1,2,3])

In [17]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

# Concatination

In [18]:
a=np.array([[1,2,3],[4,5,6]])

In [19]:
b=np.array([[7,8,9],[10,11,12]])

In [20]:
x=np.concatenate((a,b),axis=0)

In [21]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
x=np.concatenate((a,b),axis=1)

In [23]:
x

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
x=np.concatenate((a,b),axis=None)

In [27]:
print(x)
print("# arrays are flatten first then concatenate ")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
# arrays are flatten first then concatenate 


In [28]:
a=np.arange(10,20)

In [29]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
x=np.where(a>15)
x

(array([6, 7, 8, 9], dtype=int64),)

In [32]:
a[np.where(a>15)]

array([16, 17, 18, 19])

In [34]:
x=a%2==0
x

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])