In [1]:
import numpy as np

# Arrays

In [2]:
arr=np.array([1,2,3])

In [3]:
print(arr)

[1 2 3]


In [4]:
twod=np.array([[1,2,3],[4,5,6]])
print(twod)

[[1 2 3]
 [4 5 6]]


In [5]:
print(type(twod))

<class 'numpy.ndarray'>


In [6]:
arr=([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [7]:
# covnerting list into an array
list1=[1,2,3]
print(list1)
print(type(list1))

[1, 2, 3]
<class 'list'>


In [8]:
import numpy as np
arr1=np.array(list1)
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# converting array to list
back_to_list=arr1.tolist()
print(back_to_list)
print(type(back_to_list))

[1, 2, 3]
<class 'list'>


In [10]:
num=np.arange(5)
print(num)

[0 1 2 3 4]


In [11]:
num=np.arange(10,14)
print(num)

[10 11 12 13]


In [12]:
num=np.arange(10,20,2)
print(num)

[10 12 14 16 18]


In [13]:
num=np.zeros(5,dtype='int')
print(num)

[0 0 0 0 0]


In [14]:
num=np.zeros((3,3))
print(num)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [16]:
# if endpoint is false then end value is no t included
np.linspace(2.0,3.0, num=5, endpoint= False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [17]:
# retstep return step b/w the sample
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)