In [1]:
import numpy as np

# NUMPY RESHAPE=>NP.RESHAPE()

In [3]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a.ndim

1

In [6]:
arr1=np.reshape(a,(4,3),order='C')
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
arr1=np.reshape(a,(3,4),order='F')

In [8]:
arr1

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# 1D-2D

In [10]:
oneD=np.arange(8)

In [11]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
twoD=np.reshape(oneD,(2,4))

In [13]:
twoD

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
twoD.ndim

2

In [15]:
oned=np.arange(16)

In [17]:
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
threeD=np.reshape(oned,(2,4,2))

In [19]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [20]:
threeD.ndim

3

In [21]:
d2=np.zeros((4,4))

In [22]:
d2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.reshape(d2,(2,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Unknown Dimention Reshape

In [24]:
a=np.arange(10).reshape((5,2))

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
print(a.reshape((2,-1)))
print("# here -1 is calculated by the  numpy as 5 bcz total elements are 10")

[[0 1 2 3 4]
 [5 6 7 8 9]]
# here -1 is calculated by the  numpy as 5 bcz total elements are 10


In [28]:
a.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
x=np.arange(10)

In [32]:
x.reshape((-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])