In [1]:
import numpy as np

# Randomization

In [2]:
X1 = np.random.randint(0,10,15)
X2 = np.random.randint(10,20,15)
X3 = np.random.randint(20,30,15)
data=np.array([X1,X2,X3])
print(data)

[[ 7  6  6  1  3  0  0  1  6  8  1  4  9  0  6]
 [11 11 12 13 10 12 15 13 11 18 12 14 18 19 19]
 [24 20 25 26 21 28 25 28 29 26 22 21 21 24 25]]


In [4]:
np.eye(2)
#  np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

array([[1., 0.],
       [0., 1.]])

In [5]:
import time

In [9]:
SIZE=1000000
L1=range(SIZE)
L2=range(SIZE)

In [10]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

# for list time taken

In [12]:
start=time.time()
result=[(x+y)for x,y in zip(L1,L2)]
end=time.time()
print((end-start)*1000)

251.692533493042


# for numpy time taken

In [14]:
start=time.time()
result=A1+A2
end=time.time()
print((end-start)*1000)
print("# now see that the numpy is more speedy than a python list")

0.0
# now see that the numpy is more speedy than a python list


# Dimentions

In [15]:
a=np.array([1,2,3])
a.ndim

1

In [16]:
numpy=np.array([1,2,3])
numpy.itemsize

4

In [17]:
numpy.size

3

In [18]:
# shape of the arrays
numpy=np.array([[1,2,3],[4,5,6]])
numpy.shape

(2, 3)

In [19]:
numpy=np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy.shape

(3, 3)

In [20]:
numpy.ndim

2

In [22]:
three_D=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [24]:
three_D.ndim

3

In [26]:
three_D.shape

(2, 2, 3)

In [27]:
a=np.array([1,2,3])
a.itemsize

4

In [30]:
a=np.array([1,2,3])
print(a.size)
print("# size => tells the number of elements in the array")

3
# size => tells the number of elements in the array


In [31]:
numpy=np.array([[1,2,3],[4,5,6]])
numpy.size

6