In [1]:
import numpy as np

# Stacking in Numpy

In [2]:
a=([1,4,5])

In [3]:
b=([5,6,7])

In [4]:
np.vstack((a,b))

array([[1, 4, 5],
       [5, 6, 7]])

In [5]:
np.hstack((a,b))

array([1, 4, 5, 5, 6, 7])

# spliting of the array

In [7]:
a=np.arange(10)

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# it will split the array into same 2 parts
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [10]:
# it will split the array at position 3
np.split(a,[3])

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [11]:
# it will split the array at position 3 and position 6
np.split(a,[3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

# Arithimatic operations

In [12]:
a=np.array([1,2,3])

In [13]:
b=np.array([4,5,6])

In [14]:
np.add(a,b)

array([5, 7, 9])

In [15]:
np.subtract(a,b)

array([-3, -3, -3])

In [16]:
np.multiply(a,b)

array([ 4, 10, 18])

In [17]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [18]:
np.mod(a,b)

array([1, 2, 3])

In [19]:
np.power(a,b)

array([  1,  32, 729])

In [20]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
np.max(a)

9

In [22]:
np.min(a)

1

In [23]:
np.std(a)

2.581988897471611

In [24]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])