In [1]:
import numpy as np

# ndarray.base

In [2]:
x=np.array([10,20,30])

In [3]:
x

array([10, 20, 30])

In [4]:
print(x.base)

None


In [5]:
y=x[:]

In [6]:
y

array([10, 20, 30])

In [7]:
y.base

array([10, 20, 30])

# slicing creates a view whose memory is shared with 

In [8]:
y=x.view()

In [9]:
y[1]=99

In [10]:
y

array([10, 99, 30])

In [11]:
x

array([10, 99, 30])

# Array Operations

In [12]:
a=np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
np.sum(a)

10

In [15]:
np.sum(a,axis=0)

array([4, 6])

In [16]:
np.sum(a,axis=1)

array([3, 7])

In [17]:
a=np.array([1,2,3,4,5])

In [18]:
a.prod()

120

In [19]:
a=np.array([[1,2,3],[4,5,6]])

In [20]:
a.prod(axis=0)

array([ 4, 10, 18])

In [21]:
a.prod(axis=1)

array([  6, 120])

In [22]:
a=np.array([22,33,11,12])

In [23]:
a.sort()

In [24]:
a

array([11, 12, 22, 33])

In [25]:
a=np.array([[2,1,3],[5,1,2]])

In [26]:
a

array([[2, 1, 3],
       [5, 1, 2]])