In [1]:
import numpy as np

# np.random.seed

In [2]:
np.random.randint(1,500)

270

In [3]:
np.random.seed(5)
np.random.randint(1,500)

356

In [4]:
# if we use the seed then the random value will be predictable
np.random.seed(5)
np.random.randint(1,500,10)

array([356, 207, 496, 190, 487, 119, 401,  74,   9, 229])

# reshape and transpose

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# MEAN , MEDIAN AND MODE

In [9]:
BMI=[11,24,11,15,17,22,40,30]

In [10]:
BMI

[11, 24, 11, 15, 17, 22, 40, 30]

In [12]:
mean=(sum(BMI)/8)

In [13]:
mean

21.25

In [16]:
mean_value=np.mean(BMI)

In [17]:
mean_value

21.25

In [19]:
median_value=np.median(BMI)

In [20]:
median_value

19.5

In [21]:
from scipy import stats as st

In [22]:
mode=st.mode(BMI)

In [23]:
mode

ModeResult(mode=11, count=2)

In [24]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [25]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
np.argmax(a)

11

In [27]:
np.argmin(a)

0

In [28]:
np.argmin(a,axis=0)
# here the result is array([0, 0, 0, 0] means all the min values along col is on index 0

array([0, 0, 0, 0], dtype=int64)

In [29]:
np.argmax(a,axis=0)

array([2, 2, 2, 2], dtype=int64)

In [30]:
np.argmax(a,axis=1)

array([3, 3, 3], dtype=int64)

In [31]:
np.argmin(a,axis=1)

array([0, 0, 0], dtype=int64)