In [2]:
import numpy as np

# NUMPY RESIZE AND ARRAY RESIZE

In [3]:
x=np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
v=np.resize(x,(5,3))

In [6]:
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1],
       [2, 3, 4]])

In [7]:
x.resize((5,3),refcheck=False)

In [8]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 0],
       [0, 0, 0]])

# ALIASING

In [9]:
x=np.array([10,20,30,40])

In [12]:
x

array([ 10, 999,  30,  40])

In [14]:
y=x

In [15]:
x[1]=999

In [16]:
x

array([ 10, 999,  30,  40])

In [17]:
y

array([ 10, 999,  30,  40])

In [18]:
y=np.copy(x[:])

In [19]:
y

array([ 10, 999,  30,  40])

In [20]:
x[2]=100

In [21]:
x

array([ 10, 999, 100,  40])

In [22]:
y

array([ 10, 999,  30,  40])